environment:
  global:
    BZIP2_VER: 1.0.6
    EXPAT_VER: 2.2.5
    ZLIB_VER: 1.2.11
    SHAPELY_VER: 1.6.4
    BOOST_PREFIX: C:\Libraries\boost_1_71_0
    PIPINSTALLS: nose wheel
  matrix:
    - PYTHON_VER: 3.6
      MINICONDA: "C:\\Miniconda36-x64"
      arch: x64
    - PYTHON_VER: 3.7
      MINICONDA: "C:\\Miniconda37-x64"
      arch: x64
    - PYTHON_VER: 3.8
      MINICONDA: "C:\\Miniconda38-x64"
      arch: x64

os: Visual Studio 2019

clone_depth: 1

init:
  - git config --global core.autocrlf input
  - '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall" amd64'
  - set conda_path=%MINICONDA%\Scripts
  - set conda_library_path=%MINICONDA%\envs\pyosmium\Library

install:
  - set PATH=%PATH%;%conda_path%
  - cd c:\
  - conda config --set always_yes yes
  - conda create --name pyosmium python=%PYTHON_VER%
  - activate pyosmium
  - conda install bzip2=%BZIP2_VER% expat=%EXPAT_VER% zlib=%ZLIB_VER% shapely=%SHAPELY_VER% %PIPINSTALLS%
  - SET PATH=%MINICONDA%\envs\pyosmium\Scripts;%PATH%
  - python --version
  - cd c:\dev
  - git clone --depth 1 https://github.com/osmcode/libosmium.git pyosmium/contrib/libosmium
  - git clone --depth 1 https://github.com/mapbox/protozero.git pyosmium/contrib/protozero
  - git clone --depth 1 https://github.com/pybind/pybind11.git pyosmium/contrib/pybind11

# clone directory
clone_folder: c:\dev\pyosmium

build_script:
  - cd c:\dev\pyosmium
  - python setup.py build
  - python setup.py install --user

test_script:
  - set PATH=%BOOST_PREFIX:/=\%\lib;%PATH%
  - cd test
  - python run_tests.py

after_test:
  - cd c:\dev\pyosmium
  - copy /y %conda_library_path%\bin\zlib.dll c:\dev\pyosmium\src\osmium
  - copy /y %conda_library_path%\bin\expat.dll c:\dev\pyosmium\src\osmium
  - copy /y %conda_library_path%\bin\libbz2.dll c:\dev\pyosmium\src\osmium
  - python.exe setup.py bdist_wheel

artifacts:
  - path: dist\*
